/// Country codes for the national leaderboard (SPEC §4.6).
///
/// Why a national board at all: a global top 100 is unreachable for an ordinary
/// player, so it stops being a goal after the first look. A national one is
/// winnable, which is the whole point of showing a ranking.
///
/// The code is a **hint the client derives from the device locale**, never a
/// claim about where someone is. It is not verified against the submitter's
/// address (the stored `ip_hash` is a one-way digest, and geolocating it would
/// be both wrong and a privacy step backwards), so it is validated for shape
/// only: anything that is not a currently assigned ISO 3166-1 alpha-2 code is
/// dropped and the run is stored without one. A locale oddity must never cost
/// somebody a verified score.
library;

/// `GET /api/leaderboard` (or `/rank`) was asked for a country that is not an
/// ISO 3166-1 alpha-2 code (SPEC §4.6).
///
/// Deliberately *not* the same treatment a submission gets. Dropping an unusable
/// code on the way in costs nothing — the run is still stored and still ranked
/// globally — but dropping it on the way out would answer a request for one
/// country's board with the whole world's, which is a wrong answer rather than a
/// lenient one. This mirrors `invalid_period`, which the same endpoint has always
/// refused.
const String invalidCountryError = 'invalid_country';

/// Length of an ISO 3166-1 alpha-2 code.
const int countryCodeLength = 2;

/// Every currently assigned ISO 3166-1 alpha-2 code (249 of them), uppercase.
///
/// Source: the ISO 3166-1 alpha-2 list as carried by the IANA time zone
/// database (`iso3166.tab`, current as of ISO/TC 46 N1127). Withdrawn codes
/// (`AN`, `CS`, `YU`, …) and the user-assigned range (`AA`, `QM`–`QZ`, `XA`–`XZ`,
/// `ZZ`) are deliberately absent: a device whose locale still reports one of
/// them submits without a country rather than founding a country of its own.
///
/// Membership is the only question ever asked of this set, so it stays a plain
/// `Set<String>` — no names, no flags, no translations. Naming and flag
/// rendering belong to the client, which already has the device's locale data
/// and does not need the server to ship 249 strings in six languages.
const Set<String> isoCountryCodes = {
  'AD',
  'AE',
  'AF',
  'AG',
  'AI',
  'AL',
  'AM',
  'AO',
  'AQ',
  'AR',
  'AS',
  'AT',
  'AU',
  'AW',
  'AX',
  'AZ',
  'BA',
  'BB',
  'BD',
  'BE',
  'BF',
  'BG',
  'BH',
  'BI',
  'BJ',
  'BL',
  'BM',
  'BN',
  'BO',
  'BQ',
  'BR',
  'BS',
  'BT',
  'BV',
  'BW',
  'BY',
  'BZ',
  'CA',
  'CC',
  'CD',
  'CF',
  'CG',
  'CH',
  'CI',
  'CK',
  'CL',
  'CM',
  'CN',
  'CO',
  'CR',
  'CU',
  'CV',
  'CW',
  'CX',
  'CY',
  'CZ',
  'DE',
  'DJ',
  'DK',
  'DM',
  'DO',
  'DZ',
  'EC',
  'EE',
  'EG',
  'EH',
  'ER',
  'ES',
  'ET',
  'FI',
  'FJ',
  'FK',
  'FM',
  'FO',
  'FR',
  'GA',
  'GB',
  'GD',
  'GE',
  'GF',
  'GG',
  'GH',
  'GI',
  'GL',
  'GM',
  'GN',
  'GP',
  'GQ',
  'GR',
  'GS',
  'GT',
  'GU',
  'GW',
  'GY',
  'HK',
  'HM',
  'HN',
  'HR',
  'HT',
  'HU',
  'ID',
  'IE',
  'IL',
  'IM',
  'IN',
  'IO',
  'IQ',
  'IR',
  'IS',
  'IT',
  'JE',
  'JM',
  'JO',
  'JP',
  'KE',
  'KG',
  'KH',
  'KI',
  'KM',
  'KN',
  'KP',
  'KR',
  'KW',
  'KY',
  'KZ',
  'LA',
  'LB',
  'LC',
  'LI',
  'LK',
  'LR',
  'LS',
  'LT',
  'LU',
  'LV',
  'LY',
  'MA',
  'MC',
  'MD',
  'ME',
  'MF',
  'MG',
  'MH',
  'MK',
  'ML',
  'MM',
  'MN',
  'MO',
  'MP',
  'MQ',
  'MR',
  'MS',
  'MT',
  'MU',
  'MV',
  'MW',
  'MX',
  'MY',
  'MZ',
  'NA',
  'NC',
  'NE',
  'NF',
  'NG',
  'NI',
  'NL',
  'NO',
  'NP',
  'NR',
  'NU',
  'NZ',
  'OM',
  'PA',
  'PE',
  'PF',
  'PG',
  'PH',
  'PK',
  'PL',
  'PM',
  'PN',
  'PR',
  'PS',
  'PT',
  'PW',
  'PY',
  'QA',
  'RE',
  'RO',
  'RS',
  'RU',
  'RW',
  'SA',
  'SB',
  'SC',
  'SD',
  'SE',
  'SG',
  'SH',
  'SI',
  'SJ',
  'SK',
  'SL',
  'SM',
  'SN',
  'SO',
  'SR',
  'SS',
  'ST',
  'SV',
  'SX',
  'SY',
  'SZ',
  'TC',
  'TD',
  'TF',
  'TG',
  'TH',
  'TJ',
  'TK',
  'TL',
  'TM',
  'TN',
  'TO',
  'TR',
  'TT',
  'TV',
  'TW',
  'TZ',
  'UA',
  'UG',
  'UM',
  'US',
  'UY',
  'UZ',
  'VA',
  'VC',
  'VE',
  'VG',
  'VI',
  'VN',
  'VU',
  'WF',
  'WS',
  'YE',
  'YT',
  'ZA',
  'ZM',
  'ZW',
};

/// The uppercase ISO 3166-1 alpha-2 code [raw] denotes, or null when it is not
/// one (SPEC §4.6).
///
/// Surrounding whitespace and case are forgiven, because `pl` and ` PL ` are the
/// same hint. Nothing else is: a full locale tag (`pl_PL`, `en-GB`) is **not**
/// accepted, so a client that forwards the whole locale sees its runs stored
/// without a country and with no `country` key echoed back — which is the
/// cheapest possible way to notice the mistake. Sending the region subtag alone
/// is the contract.
String? normalizeCountryCode(Object? raw) {
  if (raw is! String) return null;
  final code = raw.trim().toUpperCase();
  if (code.length != countryCodeLength) return null;
  return isoCountryCodes.contains(code) ? code : null;
}
